# Generated by Django 4.0.1 on 2022-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('language', models.CharField(default='', max_length=200)),
                ('singername', models.CharField(default='', max_length=200)),
                ('type1', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('song', models.FileField(default='', upload_to='songs')),
            ],
        ),
    ]
