# Generated by Django 4.0.1 on 2022-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(default='images/banner.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='language',
            field=models.CharField(default='Hindi', max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='singername',
            field=models.CharField(default='Mika', max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='type1',
            field=models.CharField(default='Romantic', max_length=200),
        ),
    ]
